global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bff-gateway'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8083']
        labels:
          service: 'product-service'
          tier: 'backend'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: [ 'user-service:8081' ]
        labels:
          service: 'user-service'
          tier: 'backend'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: [ 'auth-service:8084' ]
        labels:
          service: 'auth-service'
          tier: 'backend'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'order-service'
    static_configs:
      - targets: [ 'order-service:8082' ]
        labels:
          service: 'order-service'
          tier: 'backend'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
